export PULSE_LATENCY_MSEC=30

picom &
redshift &

while true; do
	/home/jamie/.scripts/dwm-status
	sleep 10s
done &

while true ; do
	xrdb "$XRESOURCES"
	# needs non-hardcoded alternative
	xrandr --output HDMI-A-0 --auto --output HDMI-A-1 --auto --left-of HDMI-A-0
	xset r rate 170 40
	wal -R
	pkill dunst ; dunst &
	feh --no-fehbg --bg-scale "$(< "${HOME}/.cache/wal/wal")"

	if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
		export $(dbus-launch --exit-with-session)
	fi

	dwm && continue || break
done
